apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-start-doing-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Virgin28/GitOps-ArgoCD.git
      targetRevision: main
      ref: values
      path: environments/dev  # This is where your override values are
    - repoURL: https://github.com/Virgin28/GitOps.git
      targetRevision: main
      path: start-doing-chart  # This contains your Helm chart and default values
      helm:
        valueFiles:
          - $values/values.yaml  # This references the values from the first source
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true